name = "itpark-room-bot"
main = "src/worker.js"
compatibility_date = "2026-09-01"
workers_dev = true

[vars]
ADMIN_IDS = "1314420035,1291869683,8794801275,423348382"
OPEN_HOUR = "8"
CLOSE_HOUR = "20"
BOOKING_DAYS = "30"
MAX_DURATION_HOURS = "4"

[[d1_databases]]
binding = "DB"
database_name = "itpark-rooms"
database_id = "d8f9349e-2c0b-4746-abad-fc0bb54fe0ff"
migrations_dir = "migrations"

[triggers]
crons = ["17 22 * * *"]
